In [13]:
import numpy as np

a = np.array([1, 2])
a.shape
b = np.array([3, 4, 5])
b.reshape(-1, 1)

array([[3],
       [4],
       [5]])

In [15]:
a * b.reshape(-1, 1)

array([[ 3,  6],
       [ 4,  8],
       [ 5, 10]])

In [17]:
b.reshape(-1, 1) * a

array([[ 3,  6],
       [ 4,  8],
       [ 5, 10]])

In [21]:
np.dot(b.reshape(-1, 1), a.reshape(1, -1))

array([[ 3,  6],
       [ 4,  8],
       [ 5, 10]])

In [23]:
np.dot(a.reshape(-1, 1), b.reshape(-1, 1))

ValueError: shapes (2,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [27]:
np.random.normal(scale=1 / 2 ** .5,
                                         size=3)

array([ 0.50458472,  0.21096651, -0.05424047])

In [30]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [32]:
b = np.array(np.arange(6)).reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [41]:
c = np.dot(a, b)
c

array([16, 22])

In [37]:
c.shape

(2,)

In [45]:
d = np.array([1, 1])
d

array([1, 1])

In [46]:
np.dot(c, d)

38

In [47]:
c * d

array([16, 22])

In [49]:
c.reshape(1, -1) * d.reshape(-1, 1)

array([[16, 22],
       [16, 22]])