In [35]:
import torch
from torch import nn
import torch.nn.functional as F
from torchvision import datasets, transforms
import numpy as np

In [55]:
model = nn.Sequential(nn.Linear(2, 3), nn.Sigmoid())

In [32]:
print(model[0].weight.data)
print(model[0].bias.data)

tensor([[ 0.4831, -0.3715],
        [ 0.4208,  0.4588],
        [-0.4957, -0.0053]])
tensor([-0.3904, -0.0948, -0.3872])


In [33]:
b = model[0].bias.data.numpy()
b[0] = 0
model[0].bias.data = torch.from_numpy(b)

In [34]:
for module in model:
    if isinstance(module, nn.Linear):
        module.bias.data.fill_(0)
        module.weight.data.normal_(std=0.11)
        print(module.weight)
        print(module.bias)

Parameter containing:
tensor([[ 0.0080, -0.0468],
        [ 0.1351, -0.1419],
        [ 0.0805,  0.1930]], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)


In [52]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [63]:
xs = torch.from_numpy(np.asarray([0.5, -0.5]))
xs = xs.double()
print(xs)

tensor([ 0.5000, -0.5000], dtype=torch.float64)


In [68]:
model.to(device)
model.eval()
xs = xs.to(device)

In [69]:
yx = model.forward(xs.float())
yx

tensor([0.7344, 0.3709, 0.3863], device='cuda:0', grad_fn=<SigmoidBackward>)

In [71]:
model_copy = type(model)() # get a new instance
model_copy.load_state_dict(model.state_dict()) # copy weights and stuff

RuntimeError: Error(s) in loading state_dict for Sequential:
	Unexpected key(s) in state_dict: "0.weight", "0.bias". 